# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Eve\Eve\tools\pm\ui\ui_pm_main.ui',
# licensing of 'E:\Eve\Eve\tools\pm\ui\ui_pm_main.ui' applies.
#
# Created: Thu Feb 06 09:03:08 2020
#      by: pyside2-uic  running on PySide2 5.9.0a1.dev1528389443
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ProjectManager(object):
    def setupUi(self, ProjectManager):
        ProjectManager.setObjectName("ProjectManager")
        ProjectManager.resize(851, 890)
        self.centralwidget = QtWidgets.QWidget(ProjectManager)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boxProjects = QtWidgets.QGroupBox(self.centralwidget)
        self.boxProjects.setMaximumSize(QtCore.QSize(150, 16777215))
        self.boxProjects.setObjectName("boxProjects")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.boxProjects)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listProjects = QtWidgets.QListView(self.boxProjects)
        self.listProjects.setObjectName("listProjects")
        self.verticalLayout.addWidget(self.listProjects)
        self.splitter = QtWidgets.QSplitter(self.boxProjects)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btnAddProject = QtWidgets.QPushButton(self.splitter)
        self.btnAddProject.setObjectName("btnAddProject")
        self.btnDelProject = QtWidgets.QPushButton(self.splitter)
        self.btnDelProject.setObjectName("btnDelProject")
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout.addWidget(self.boxProjects)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listAssets = QtWidgets.QListView(self.groupBox)
        self.listAssets.setObjectName("listAssets")
        self.verticalLayout_4.addWidget(self.listAssets)
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.btnAddAsset = QtWidgets.QPushButton(self.splitter_2)
        self.btnAddAsset.setObjectName("btnAddAsset")
        self.btnDelAsset = QtWidgets.QPushButton(self.splitter_2)
        self.btnDelAsset.setObjectName("btnDelAsset")
        self.verticalLayout_4.addWidget(self.splitter_2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.boxASS = QtWidgets.QGroupBox(self.centralwidget)
        self.boxASS.setMaximumSize(QtCore.QSize(150, 16777215))
        self.boxASS.setObjectName("boxASS")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.boxASS)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listSequences = QtWidgets.QListView(self.boxASS)
        self.listSequences.setObjectName("listSequences")
        self.verticalLayout_2.addWidget(self.listSequences)
        self.splitter_3 = QtWidgets.QSplitter(self.boxASS)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.btnAddSequence = QtWidgets.QPushButton(self.splitter_3)
        self.btnAddSequence.setObjectName("btnAddSequence")
        self.btnDelSequence = QtWidgets.QPushButton(self.splitter_3)
        self.btnDelSequence.setObjectName("btnDelSequence")
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.listShots = QtWidgets.QListView(self.boxASS)
        self.listShots.setObjectName("listShots")
        self.verticalLayout_2.addWidget(self.listShots)
        self.splitter_4 = QtWidgets.QSplitter(self.boxASS)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.btnAddShot = QtWidgets.QPushButton(self.splitter_4)
        self.btnAddShot.setObjectName("btnAddShot")
        self.btnDelShot = QtWidgets.QPushButton(self.splitter_4)
        self.btnDelShot.setObjectName("btnDelShot")
        self.verticalLayout_2.addWidget(self.splitter_4)
        self.horizontalLayout.addWidget(self.boxASS)
        self.boxProperties = QtWidgets.QGroupBox(self.centralwidget)
        self.boxProperties.setObjectName("boxProperties")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.boxProperties)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layoutProperties = QtWidgets.QVBoxLayout()
        self.layoutProperties.setObjectName("layoutProperties")
        self.verticalLayout_3.addLayout(self.layoutProperties)
        self.horizontalLayout.addWidget(self.boxProperties)
        ProjectManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProjectManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEve = QtWidgets.QMenu(self.menubar)
        self.menuEve.setObjectName("menuEve")
        ProjectManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProjectManager)
        self.statusbar.setObjectName("statusbar")
        ProjectManager.setStatusBar(self.statusbar)
        self.actionEveDocs = QtWidgets.QAction(ProjectManager)
        self.actionEveDocs.setObjectName("actionEveDocs")
        self.actionSettings = QtWidgets.QAction(ProjectManager)
        self.actionSettings.setObjectName("actionSettings")
        self.actionCreateDatabase = QtWidgets.QAction(ProjectManager)
        self.actionCreateDatabase.setObjectName("actionCreateDatabase")
        self.menuHelp.addAction(self.actionEveDocs)
        self.menuEve.addAction(self.actionSettings)
        self.menubar.addAction(self.menuEve.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ProjectManager)
        QtCore.QMetaObject.connectSlotsByName(ProjectManager)

    def retranslateUi(self, ProjectManager):
        ProjectManager.setWindowTitle(QtWidgets.QApplication.translate("ProjectManager", "Eve Project Manager", None, -1))
        self.boxProjects.setTitle(QtWidgets.QApplication.translate("ProjectManager", "Projects", None, -1))
        self.btnAddProject.setText(QtWidgets.QApplication.translate("ProjectManager", "+", None, -1))
        self.btnDelProject.setText(QtWidgets.QApplication.translate("ProjectManager", "-", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("ProjectManager", "Assets", None, -1))
        self.btnAddAsset.setText(QtWidgets.QApplication.translate("ProjectManager", "+", None, -1))
        self.btnDelAsset.setText(QtWidgets.QApplication.translate("ProjectManager", "-", None, -1))
        self.boxASS.setTitle(QtWidgets.QApplication.translate("ProjectManager", "Sequences | Shots", None, -1))
        self.btnAddSequence.setText(QtWidgets.QApplication.translate("ProjectManager", "+", None, -1))
        self.btnDelSequence.setText(QtWidgets.QApplication.translate("ProjectManager", "-", None, -1))
        self.btnAddShot.setText(QtWidgets.QApplication.translate("ProjectManager", "+", None, -1))
        self.btnDelShot.setText(QtWidgets.QApplication.translate("ProjectManager", "-", None, -1))
        self.boxProperties.setTitle(QtWidgets.QApplication.translate("ProjectManager", "Properties", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("ProjectManager", "Help", None, -1))
        self.menuEve.setTitle(QtWidgets.QApplication.translate("ProjectManager", "Eve", None, -1))
        self.actionEveDocs.setText(QtWidgets.QApplication.translate("ProjectManager", "Eve Documentation", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("ProjectManager", "Settings", None, -1))
        self.actionCreateDatabase.setText(QtWidgets.QApplication.translate("ProjectManager", "Create Database", None, -1))

